// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceScreenCatalog: ReferenceCatalogEntry[] = [
	{
		id: "ref-detail-confirmation",
		situation:
			"사용자가 결제를 실행하기 직전에 주문자·상품·할인·포인트·결제 수단·약관을 한 화면에서 최종 확정한다",
		tags: [
			"detail-confirmation",
			"irreversible-action",
			"summary-first",
			"payment-execution",
			"agreement-gate",
		],
		sotNodeRef: "10161:49136",
		sourceRef: "../docs/skills/references/screens/ref-detail-confirmation.md",
	},
];
