import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { SkillsetCatalogEntry } from "../../packages/agent/src/skillset-catalog/types";

const ROOT = resolve(import.meta.dirname, "..", "..");
const AGENT = join(ROOT, "packages", "agent");
const MANIFEST_DIR = join(AGENT, "docs", "skills", "skillsets");
const SRC_DIR = join(AGENT, "src");
const OUT_FILE = join(SRC_DIR, "skillset-catalog", "catalog.generated.ts");

const GEN_HEADER =
	"// AUTO-GENERATED by scripts/sync-skillset-catalog — DO NOT EDIT. Run `pnpm sync:skillset`.";

const DOCUMENT_KINDS = new Set(["prompt", "skill"]);

// 의도적 포크: sync-reference-catalog와 동일한 이유로 런타임 parseMarkdownFrontmatter의
// 별개 사본이다. documents는 `- <kind> <sourceRef>` 평면 문자열 리스트로만 파싱한다.
function parseFrontmatter(body: string): Record<string, unknown> {
	if (!body.startsWith("---\n")) return {};
	const end = body.indexOf("\n---", 4);
	if (end < 0) return {};
	const fm: Record<string, unknown> = {};
	let listKey: string | undefined;
	for (const raw of body.slice(4, end).split("\n")) {
		const line = raw.trimEnd();
		if (!line.trim()) continue;
		if (line.trimStart().startsWith("- ") && listKey) {
			const items = Array.isArray(fm[listKey]) ? (fm[listKey] as string[]) : [];
			items.push(line.trimStart().slice(2).trim());
			fm[listKey] = items;
			continue;
		}
		listKey = undefined;
		const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
		if (!m) continue;
		const [, key, value] = m;
		if (value.length === 0) {
			fm[key] = [];
			listKey = key;
			continue;
		}
		fm[key] = value.replace(/^["']|["']$/g, "");
	}
	return fm;
}

function parseDocumentLine(file: string, line: string): SkillsetCatalogEntry["documents"][number] {
	const [kind, sourceRef, ...rest] = line.split(/\s+/);
	if (!kind || !sourceRef || rest.length > 0) {
		throw new Error(`${file}: invalid document line '${line}' — expected '<kind> <sourceRef>'`);
	}
	if (!DOCUMENT_KINDS.has(kind)) {
		throw new Error(`${file}: unknown document kind '${kind}' in '${line}'`);
	}
	if (!existsSync(resolve(SRC_DIR, sourceRef))) {
		throw new Error(
			`${file}: document not found at '${sourceRef}' (relative to packages/agent/src)`,
		);
	}
	return { kind: kind as "prompt" | "skill", sourceRef };
}

function collect(): Record<string, SkillsetCatalogEntry> {
	const files = readdirSync(MANIFEST_DIR)
		.filter((f) => f.endsWith(".md"))
		.sort();
	const catalog: Record<string, SkillsetCatalogEntry> = {};
	for (const file of files) {
		const task = file.replace(/\.md$/, "");
		const fm = parseFrontmatter(readFileSync(join(MANIFEST_DIR, file), "utf8"));
		const lines = Array.isArray(fm.documents) ? (fm.documents as string[]) : [];
		if (lines.length === 0) {
			throw new Error(`${file}: frontmatter 'documents' must be a non-empty list`);
		}
		catalog[task] = {
			documents: lines.map((line) => parseDocumentLine(file, line)),
		};
	}
	if (Object.keys(catalog).length === 0) {
		throw new Error(`no skillset manifests found in ${MANIFEST_DIR}`);
	}
	return catalog;
}

function emitCatalog(catalog: Record<string, SkillsetCatalogEntry>): string {
	const entries = Object.entries(catalog)
		.map(([task, entry]) => {
			const documents = entry.documents
				.map(
					(d) =>
						`\t\t\t{ kind: ${JSON.stringify(d.kind)}, sourceRef: ${JSON.stringify(d.sourceRef)} }`,
				)
				.join(",\n");
			return [`\t${JSON.stringify(task)}: {`, `\t\tdocuments: [`, documents, `\t\t],`, `\t}`].join(
				"\n",
			);
		})
		.join(",\n");
	return [
		GEN_HEADER,
		'import type { SkillsetCatalogEntry } from "./types";',
		"",
		"export const AGENT_SKILLSET_CATALOG = {",
		entries,
		"} as const satisfies Record<string, SkillsetCatalogEntry>;",
		"",
	].join("\n");
}

function main() {
	const catalog = collect();
	writeFileSync(OUT_FILE, emitCatalog(catalog), "utf8");
	execFileSync(join(ROOT, "node_modules", ".bin", "biome"), ["format", "--write", OUT_FILE], {
		stdio: "ignore",
	});
	// eslint-disable-next-line no-console
	console.log(`sync-skillset-catalog: ${Object.keys(catalog).length} skillsets`);
}

// import-safe: 테스트가 collect를 import해도 main()이 돌지 않는다.
export { collect };

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
	main();
}
