import type { CompositeWrapperDefaults } from "./CompositeWrapper";

// composite defaults는 component-land에 둔다(area presets와 동일 정책). catalog는 계약만 소유.
export const compositeDefaults = {
	componentAppBar: { gap: 0 },
	componentThumbnailLarge: { gap: 0 },
	componentTextField: { gap: 0 },
	componentSectionMessage: { gap: 0 },
	componentButton: { gap: 0 },
	componentListCell: { gap: 0 },
	componentAccordion: { gap: 0 },
	componentCheckbox: { gap: 0 },
	componentProductInfo: { gap: 8, paddingX: 32 },
	componentCardSummary: { gap: 0 },
	componentBadge: { gap: 0 },
	componentTextButton: { gap: 0 },
	componentListText: { gap: 0 },
	componentOptionCard: { gap: 4, minHeight: 74 },
	componentBannerIndicator: { gap: 10, height: 112, width: 369 },
	componentFooter: { gap: 8 },
	componentLegalText: { gap: 6 },
	componentMapBlock: { gap: 0 },
	componentStoreCard: { gap: 0 },
	componentTitleSection: { gap: 0 },
	componentInfoTextList: { gap: 0, height: 71 },
	componentChipFilter: { flow: "horizontal", gap: 8, height: 57, paddingX: 32 },
	componentTab: { flow: "horizontal", gap: 0, height: 47 },
	componentSearchBar: { gap: 0, height: 61 },
	componentAccordionNoticeInfo: { gap: 0 },
	compositeTitleInfoTextList: { gap: 0 },
	compositeSummaryFilteredTextList: { gap: 0 },
	compositeSummarySectionedInfoList: { gap: 0 },
	compositePlainNoticeList: { gap: 0, paddingX: 32 },
	compositeTabChipSearchAccordionList: { gap: 0 },
	compositeProductHeroMediaInfo: { gap: 0 },
	compositeProductSummaryStatusList: { gap: 12 },
	compositeStoreMapList: { gap: 8 },
	compositeFooterLegalLinks: { gap: 30 },
	compositeProductListFilterSort: { gap: 0 },
	compositeProductListGroupTitleStack: { gap: 16 },
	compositeListProductHorizontalCardSet: { gap: 12 },
	compositeListProductRowCardSet: { gap: 12 },
	compositePagestackProductCardList: { gap: 0 },
	componentActionButton: { gap: 0 },
	componentActionButtonWithTooltip: { gap: 10 },
	compositePriceAccordionSelectedList: { gap: 0 },
	compositeProductDetailRichImageTab: { gap: 0 },
	compositeButtonMoreProductLink: { gap: 0 },
	compositeOptionListStack: { gap: 8 },
	compositeCouponBenefitCard: { gap: 12 },
	compositeMapCardInfoList: { gap: 8 },
	compositeCardInfoBrandList: { gap: 8 },
	compositeProductDisclosureNoticeList: { gap: 0 },
} as const satisfies Record<string, CompositeWrapperDefaults>;
