// AUTO-GENERATED by scripts/sync-skillset-catalog — DO NOT EDIT. Run `pnpm sync:skillset`.
import type { SkillsetCatalogEntry } from "./types";

export const AGENT_SKILLSET_CATALOG = {
	"component-proposal": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/component-proposal.md" },
			{ kind: "skill", sourceRef: "../docs/skills/component-proposal/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/source-fidelity-review/README.md" },
		],
	},
	"composition-planning": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/composition-planning.md" },
			{ kind: "skill", sourceRef: "../docs/skills/design-skills/design-fundamentals/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/generate-skills/divider-usage-rules/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/compose-skills/pagestack-section-unit/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/pattern-fit-review/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/review-skills/visual-hierarchy-review/README.md",
			},
		],
	},
	"quality-review": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/quality-review.md" },
			{ kind: "skill", sourceRef: "../docs/skills/quality-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/design-skills/design-fundamentals/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/review-skills/visual-hierarchy-review/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/source-fidelity-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/pattern-fit-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/action-clarity-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/density-fit-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/state-coverage-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/anti-slop-review/README.md" },
		],
	},
	"screen-generation": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/screen-generation.md" },
			{ kind: "skill", sourceRef: "../docs/skills/design-skills/design-fundamentals/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/generate-skills/component-layout-ref/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/generate-skills/divider-usage-rules/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/generate-skills/section-divider-rhythm/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/generate-skills/bottom-fixed-cta/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/generate-skills/text-field-states/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/generate-skills/text-field-inline-action/README.md",
			},
		],
	},
	"screen-intent": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/screen-intent.md" },
			{ kind: "skill", sourceRef: "../docs/skills/design-skills/design-fundamentals/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/source-fidelity-review/README.md" },
			{ kind: "skill", sourceRef: "../docs/skills/review-skills/state-coverage-review/README.md" },
		],
	},
	"screen-revision": {
		documents: [
			{ kind: "prompt", sourceRef: "../docs/prompts/screen-revision.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/revision-skills/fix-invalid-layout-id/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/revision-skills/fix-source-ref-loss/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/revision-skills/fix-state-coverage-gap/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/revision-skills/fix-section-rhythm/README.md" },
			{
				kind: "skill",
				sourceRef: "../docs/skills/revision-skills/fix-bottom-cta-gating/README.md",
			},
			{
				kind: "skill",
				sourceRef: "../docs/skills/revision-skills/fix-component-contract-violation/README.md",
			},
			{ kind: "skill", sourceRef: "../docs/skills/revision-skills/fix-density-overload/README.md" },
		],
	},
} as const satisfies Record<string, SkillsetCatalogEntry>;
