import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { REFERENCE_CATEGORIES } from "../../packages/agent/src/reference-catalog/categories";
import type { ReferenceCatalogEntry } from "../../packages/schema/src/reference-catalog";

const ROOT = resolve(import.meta.dirname, "..", "..");
const AGENT = join(ROOT, "packages", "agent");

const GEN_HEADER =
	"// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.";

// packages/agent/src 기준 상대경로 (readAgentMarkdownDocument 규약: "../docs/...")
function sourceRefOf(categoryDir: string, file: string): string {
	return `../${categoryDir}/${file}`;
}

// 의도적 포크: 런타임 헬퍼 packages/agent/src/docs/package-markdown.ts의 parseMarkdownFrontmatter와
// 별개 사본이다(빌드 스크립트가 published 패키지 내부를 import하는 의존 방향을 피하려고). 단,
// 이쪽만 인라인 배열(`tags: [a, b]`)을 배열로 파싱한다 — 런타임 버전은 그걸 문자열로 둔다.
// 새 .md는 YAML 블록 리스트(`- item`)로 tags를 쓰는 것을 권장(양쪽 동일 결과). 인라인 배열 동작
// 차이를 버그로 오인하지 말 것.
function parseFrontmatter(body: string): Record<string, unknown> {
	if (!body.startsWith("---\n")) return {};
	const end = body.indexOf("\n---", 4);
	if (end < 0) return {};
	const fm: Record<string, unknown> = {};
	let listKey: string | undefined;
	for (const raw of body.slice(4, end).split("\n")) {
		const line = raw.trimEnd();
		if (!line.trim()) continue;
		if (line.trimStart().startsWith("- ") && listKey) {
			const items = Array.isArray(fm[listKey]) ? (fm[listKey] as string[]) : [];
			items.push(line.trimStart().slice(2).trim());
			fm[listKey] = items;
			continue;
		}
		listKey = undefined;
		const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
		if (!m) continue;
		const [, key, value] = m;
		if (value.length === 0) {
			fm[key] = [];
			listKey = key;
			continue;
		}
		if (value.startsWith("[") && value.endsWith("]")) {
			fm[key] = value
				.slice(1, -1)
				.split(",")
				.map((s) => s.trim())
				.filter(Boolean);
			continue;
		}
		fm[key] = value.replace(/^["']|["']$/g, "");
	}
	return fm;
}

function collect(categoryDir: string): ReferenceCatalogEntry[] {
	const abs = join(AGENT, categoryDir);
	const files = readdirSync(abs)
		.filter((f) => f.endsWith(".md"))
		.sort();
	const seen = new Set<string>();
	return files.map((file) => {
		const fm = parseFrontmatter(readFileSync(join(abs, file), "utf8"));
		const id = fm.id;
		if (typeof id !== "string" || id.length === 0) {
			throw new Error(`${categoryDir}/${file}: missing frontmatter \`id\``);
		}
		if (seen.has(id)) throw new Error(`${categoryDir}/${file}: duplicate id '${id}'`);
		seen.add(id);
		return {
			id,
			situation: typeof fm.situation === "string" ? fm.situation : "",
			tags: Array.isArray(fm.tags) ? (fm.tags as string[]) : [],
			...(typeof fm.sotNodeRef === "string" ? { sotNodeRef: fm.sotNodeRef } : {}),
			sourceRef: sourceRefOf(categoryDir, file),
		};
	});
}

function emitCatalog(category: string, entries: ReferenceCatalogEntry[]): string {
	const constName = `reference${category[0].toUpperCase()}${category.slice(1)}Catalog`;
	const body = entries
		.map((e) => {
			const parts = [
				`\t\tid: ${JSON.stringify(e.id)}`,
				`\t\tsituation: ${JSON.stringify(e.situation)}`,
				`\t\ttags: ${JSON.stringify(e.tags)}`,
				...(e.sotNodeRef ? [`\t\tsotNodeRef: ${JSON.stringify(e.sotNodeRef)}`] : []),
				`\t\tsourceRef: ${JSON.stringify(e.sourceRef)}`,
			];
			return `\t{\n${parts.join(",\n")},\n\t}`;
		})
		.join(",\n");
	return [
		GEN_HEADER,
		'import type { ReferenceCatalogEntry } from "../../../../src/reference-catalog/types";',
		"",
		`export const ${constName}: ReferenceCatalogEntry[] = [`,
		body,
		"];",
		"",
	].join("\n");
}

function main() {
	const generated: string[] = [];
	for (const [category, dir] of Object.entries(REFERENCE_CATEGORIES)) {
		const entries = collect(dir);
		const out = join(AGENT, dir, "catalog.generated.ts");
		writeFileSync(out, emitCatalog(category, entries), "utf8");
		generated.push(out);
	}
	execFileSync(join(ROOT, "node_modules", ".bin", "biome"), ["format", "--write", ...generated], {
		stdio: "ignore",
	});
	// eslint-disable-next-line no-console
	console.log(`sync-reference-catalog: ${generated.length} categories`);
}

// import-safe: 테스트가 collect를 import해도 main()이 돌지 않는다.
export { collect };

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
	main();
}
