/**
 * kiki 컴포넌트 소스에서 catalog.ts를 자동 생성한다.
 *
 * - barrel export → source: "kiki-barrel", label: "[kiki] ComponentName"
 * - 그 외        → source: "kiki-draft",   label: "[kiki/draft] ComponentName"
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseProps } from "./parse-props.ts";

export interface GenCatalogOptions {
	/** packages/external/src 절대 경로 */
	externalSrcDir: string;
	/** barrel에서 파싱한 공식 export 이름 목록 */
	barrelExports: string[];
	/** 출력 경로 (packages/external/src/catalog.ts) */
	outputPath: string;
}

export function genCatalog(opts: GenCatalogOptions): number {
	const { externalSrcDir, barrelExports, outputPath } = opts;
	const barrelSet = new Set(barrelExports);
	const componentsDir = join(externalSrcDir, "components");

	if (!existsSync(componentsDir)) {
		throw new Error(`components 디렉토리 없음: ${componentsDir}`);
	}

	const componentNames = readdirSync(componentsDir, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name)
		.sort();

	const entries: string[] = [];

	for (const name of componentNames) {
		const tsxPath = join(componentsDir, name, `${name}.tsx`);
		if (!existsSync(tsxPath)) continue;

		const isBarrel = barrelSet.has(name);
		const source = isBarrel ? "kiki-barrel" : "kiki-draft";
		const label = isBarrel ? `[kiki] ${name}` : `[kiki/draft] ${name}`;
		const typeKey = `kiki.${name}`;

		let props: ReturnType<typeof parseProps> = [];
		try {
			props = parseProps(tsxPath);
		} catch {
			// 파싱 실패 시 빈 props로 진행
		}

		const propsEntries = props
			.map((p) => {
				const contract: string[] = [`type: "${p.type}"`];
				if (p.values && p.values.length > 0) {
					contract.push(`values: [${p.values.map((v) => `"${v}"`).join(", ")}]`);
				}
				if (!p.required) {
					// optional → defaultValue 없으면 required: false 명시
					contract.push(`required: false`);
				} else {
					contract.push(`required: true`);
				}
				return `\t\t\t${p.name}: { ${contract.join(", ")} },`;
			})
			.join("\n");

		entries.push(`\t"${typeKey}": {
\t\ttype: "${typeKey}",
\t\tsource: "${source}",
\t\tlabel: "${label}",
\t\tversion: "0.0.0",
\t\tprops: {
${propsEntries}
\t\t},
\t},`);
	}

	const output = `// AUTO-GENERATED by scripts/sync-catalog — DO NOT EDIT MANUALLY
// Run \`pnpm sync:catalog\` to regenerate

import type { ComponentCatalog } from "@cx/types/component-catalog";

export const externalCatalog: ComponentCatalog = {
${entries.join("\n")}
};
`;

	writeFileSync(outputPath, output, "utf8");
	return componentNames.length;
}
