/**
 * 렌더러가 import 할 kiki 컴포넌트 표면(registry.generated.ts)을 자동 생성한다.
 *
 * 배경: vendored 된 kiki의 index.ts(barrel)는 공식 컴포넌트만 export 한다. draft 컴포넌트는
 * 디렉토리에 파일로만 존재해 `import * from "@cx/external"` 로는 렌더 함수를 못 찾고 fallback(라벨만)
 * 으로 그려진다. catalog/팔레트는 87개를 모두 노출하므로 렌더 표면을 넓혀야 한다.
 *
 * 단, kiki는 Vite 기반이라 이미지 import(`import x from './x.png'`)가 string URL 이라고 가정한다.
 * Next/Turbopack 은 이미지를 디코드해 StaticImageData 로 만들고(타입 불일치) + 일부 kiki PNG는
 * IDAT CRC가 어긋난 파일이라 디코더가 빌드를 깨뜨린다. 이 문제를 어댑터로 우회하는 대신,
 * "이미지를 (전이적으로도) 쓰지 않는 컴포넌트"만 골라 export 한다 — Next에서 그대로 깨끗이 렌더된다.
 *
 * 제외된 컴포넌트(이미지 사용 / dir명과 다른 export)는 팔레트엔 남지만 렌더는 fallback(라벨) 처리된다.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export interface GenRegistryOptions {
	/** packages/external/src 절대 경로 */
	externalSrcDir: string;
	/** 출력 경로 (packages/external/src/registry.generated.ts) */
	outputPath: string;
}

export interface GenRegistryResult {
	exported: number;
	/** 렌더 제외 + 이유 */
	skipped: Array<{ name: string; reason: "no-export" | "image" }>;
}

const IMAGE_IMPORT = /import\s+\w+\s+from\s+['"][^'"]+\.(?:png|jpe?g|svg|webp|gif)['"]/;

export function genRegistry(opts: GenRegistryOptions): GenRegistryResult {
	const { externalSrcDir, outputPath } = opts;
	const componentsDir = join(externalSrcDir, "components");
	if (!existsSync(componentsDir)) {
		throw new Error(`components 디렉토리 없음: ${componentsDir}`);
	}

	const names = readdirSync(componentsDir, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name)
		.sort();
	const nameSet = new Set(names);

	// 각 컴포넌트의 소스 읽기 + 직접 이미지 import 여부 + 형제 컴포넌트 import 수집
	const exportsDirName = new Map<string, boolean>();
	const directImage = new Map<string, boolean>();
	const siblingImports = new Map<string, Set<string>>();

	for (const name of names) {
		const tsx = join(componentsDir, name, `${name}.tsx`);
		if (!existsSync(tsx)) {
			exportsDirName.set(name, false);
			directImage.set(name, false);
			siblingImports.set(name, new Set());
			continue;
		}
		const src = readFileSync(tsx, "utf8");
		exportsDirName.set(name, new RegExp(`export\\s+(?:function|const)\\s+${name}\\b`).test(src));
		directImage.set(name, IMAGE_IMPORT.test(src));

		const sibs = new Set<string>();
		const relImport = /from\s+['"]\.\.?\/([A-Za-z0-9_]+)/g;
		for (let m = relImport.exec(src); m !== null; m = relImport.exec(src)) {
			if (nameSet.has(m[1])) sibs.add(m[1]);
		}
		siblingImports.set(name, sibs);
	}

	// 전이적 이미지 오염 판정 — 자신 또는 형제 import 체인 어딘가에서 이미지를 쓰면 오염
	const taintCache = new Map<string, boolean>();
	function taints(name: string, stack: Set<string>): boolean {
		if (directImage.get(name)) return true;
		if (taintCache.has(name)) return taintCache.get(name)!;
		if (stack.has(name)) return false; // 순환 — 이 경로에서는 추가 오염 없음
		stack.add(name);
		const tainted = [...(siblingImports.get(name) ?? [])].some((s) => taints(s, stack));
		stack.delete(name);
		taintCache.set(name, tainted);
		return tainted;
	}

	const lines: string[] = [];
	const skipped: GenRegistryResult["skipped"] = [];

	for (const name of names) {
		if (!exportsDirName.get(name)) {
			skipped.push({ name, reason: "no-export" });
			continue;
		}
		if (taints(name, new Set())) {
			skipped.push({ name, reason: "image" });
			continue;
		}
		lines.push(`export { ${name} } from "./components/${name}/${name}";`);
	}

	const output = `// AUTO-GENERATED by scripts/sync-catalog — DO NOT EDIT MANUALLY
// Run \`pnpm sync:catalog\` to regenerate
// 렌더러용 컴포넌트 표면. catalog의 "kiki.{name}"와 매칭된다.
// 이미지를 (전이적으로도) 쓰지 않아 Next에서 깨끗이 렌더되는 컴포넌트만 포함한다.

${lines.join("\n")}
`;
	writeFileSync(outputPath, output, "utf8");
	return { exported: lines.length, skipped };
}
