/**
 * [KIKI-SHIM] 임시 — kiki 빌드 제공 시 이 생성기 + 산출물(registry.generated.ts) 삭제,
 * kiki 빌드물의 barrel(@cx/external) 을 직접 쓴다. 제거 가이드: packages/external/KIKI-SHIM.md
 *
 * 렌더러가 import 할 kiki 컴포넌트 표면(registry.generated.ts)을 자동 생성한다.
 *
 * 배경: vendored 된 kiki의 index.ts(barrel)는 공식 컴포넌트만 export 한다. draft 컴포넌트는
 * 디렉토리에 파일로만 존재해 `import * from "@cx/external"` 로는 렌더 함수를 못 찾고 fallback(라벨만)
 * 으로 그려진다. catalog/팔레트는 87개를 모두 노출하므로 렌더 표면도 넓혀 전부 export 한다.
 *
 * 이미지 import 문제(kiki는 Vite 기반 string URL 기대, 일부 PNG는 CRC 깨짐)는
 * next.config 의 `images.disableStaticImages` 로 해소한다(이미지 = URL 문자열, 디코드 안 함).
 *
 * catalog 의 type 키는 디렉토리명("kiki.{dir}") 이므로, dir 과 같은 이름으로 export 하는
 * 컴포넌트만 안전하게 re-export 한다. (예: Checkbox/Radio 는 CheckboxItem/RadioItem 등으로만
 * export 해 dir 명과 일치하는 심볼이 없어 제외 — 이 경우 해당 type 은 fallback 렌더된다.)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface GenRegistryOptions {
	/** packages/external/src 절대 경로 */
	externalSrcDir: string;
	/** 출력 경로 (packages/external/src/registry.generated.ts) */
	outputPath: string;
}

export interface GenRegistryResult {
	exported: number;
	/** dir명과 일치하는 export 가 없어 제외된 컴포넌트 */
	skipped: string[];
}

export function genRegistry(opts: GenRegistryOptions): GenRegistryResult {
	const { externalSrcDir, outputPath } = opts;
	const componentsDir = join(externalSrcDir, "components");
	if (!existsSync(componentsDir)) {
		throw new Error(`components 디렉토리 없음: ${componentsDir}`);
	}

	const names = readdirSync(componentsDir, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name)
		.sort();

	const lines: string[] = [];
	const skipped: string[] = [];

	for (const name of names) {
		const tsx = join(componentsDir, name, `${name}.tsx`);
		if (!existsSync(tsx)) {
			skipped.push(name);
			continue;
		}
		const src = readFileSync(tsx, "utf8");
		const exportsDirName = new RegExp(`export\\s+(?:function|const)\\s+${name}\\b`).test(src);
		if (!exportsDirName) {
			skipped.push(name);
			continue;
		}
		lines.push(`export { ${name} } from "./components/${name}/${name}";`);
	}

	const output = `// [KIKI-SHIM] 임시 — kiki 빌드 제공 시 삭제. 제거 가이드: packages/external/KIKI-SHIM.md
// AUTO-GENERATED by scripts/sync-catalog — DO NOT EDIT MANUALLY
// Run \`pnpm sync:catalog\` to regenerate
// 렌더러용 전체 컴포넌트 표면. catalog의 "kiki.{name}"와 매칭된다.

${lines.join("\n")}
`;
	writeFileSync(outputPath, output, "utf8");
	return { exported: lines.length, skipped };
}
