import type {
	ComponentCatalog,
	ComponentCatalogEntry,
} from "../../packages/schema/src/component-catalog";

/**
 * catalog.source.ts(큐레이션 SSOT)의 엔트리 — label은 source에서 파생되므로 받지 않는다.
 * description, props role 같은 큐레이션 데이터는 TSX에서 유도할 수 없어 소스 파일이 정본이다.
 */
export type CatalogSourceEntry = Omit<ComponentCatalogEntry, "label">;

export function deriveLabel(entry: CatalogSourceEntry): string {
	const name = entry.type.replace(/^kiki\./, "");
	return entry.source === "kiki-barrel" ? `[kiki] ${name}` : `[kiki/draft] ${name}`;
}

export function deriveCatalog(source: Record<string, CatalogSourceEntry>): ComponentCatalog {
	return Object.fromEntries(
		Object.entries(source).map(([key, entry]) => {
			const { type, source: entrySource, version, description, kind, props, tokens } = entry;
			return [
				key,
				{
					type,
					source: entrySource,
					label: deriveLabel(entry),
					version,
					...(description !== undefined ? { description } : {}),
					...(kind !== undefined ? { kind } : {}),
					props,
					...(tokens !== undefined ? { tokens } : {}),
				},
			];
		}),
	);
}

/** 카탈로그 엔트리 ↔ components/ 디렉터리 1:1 드리프트 가드. 위반 목록을 돌려준다. */
export function findCatalogDrift(
	source: Record<string, CatalogSourceEntry>,
	componentDirNames: string[],
): string[] {
	const problems: string[] = [];
	const dirs = new Set(componentDirNames);
	const entryNames = new Set<string>();

	for (const [key, entry] of Object.entries(source)) {
		if (entry.type !== key) {
			problems.push(`entry key '${key}' does not match its type '${entry.type}'`);
		}
		const m = /^kiki\.(.+)$/.exec(key);
		if (!m) {
			problems.push(`entry key '${key}' must be shaped as 'kiki.<ComponentName>'`);
			continue;
		}
		entryNames.add(m[1]);
		if (!dirs.has(m[1])) {
			problems.push(`entry '${key}' has no component directory components/${m[1]}/`);
		}
	}
	for (const dir of componentDirNames) {
		if (!entryNames.has(dir)) {
			problems.push(`component directory components/${dir}/ has no catalog entry 'kiki.${dir}'`);
		}
	}
	return problems;
}

/**
 * 컴포넌트 파일의 실제 export 이름이 디렉터리 이름과 다른 경우의 alias.
 * registry export 이름은 componentExportNameOf("kiki.X") = "X"와 일치해야 한다.
 */
const REGISTRY_EXPORT_ALIASES: Record<string, string> = {
	Checkbox: "CheckboxText",
	Radio: "RadioText",
};

export function buildRegistryModule(componentDirNames: string[]): string {
	const lines = [...componentDirNames].sort().map((name) => {
		const exported = REGISTRY_EXPORT_ALIASES[name];
		const specifier = exported ? `${exported} as ${name}` : name;
		return `export { ${specifier} } from "./components/${name}/${name}";`;
	});
	return [
		"// [KIKI-SHIM] 임시 — kiki 빌드 제공 시 삭제. 제거 가이드: packages/external/KIKI-SHIM.md",
		"// AUTO-GENERATED by scripts/sync-catalog — DO NOT EDIT MANUALLY",
		"// Run `pnpm sync:catalog` to regenerate",
		'// 렌더러용 전체 컴포넌트 표면. catalog의 "kiki.{name}"와 매칭된다.',
		"",
		...lines,
		"",
	].join("\n");
}

export function buildCatalogModule(catalog: ComponentCatalog): string {
	return [
		"// AUTO-GENERATED by scripts/sync-catalog — DO NOT EDIT MANUALLY",
		"// Run `pnpm sync:catalog` to regenerate",
		"",
		'import type { ComponentCatalog } from "@cx/schema";',
		"",
		`export const externalCatalog: ComponentCatalog = ${serializeTs(catalog, 0)};`,
		"",
	].join("\n");
}

export function buildCatalogSourceModule(source: Record<string, CatalogSourceEntry>): string {
	return [
		"// 컴포넌트 카탈로그의 큐레이션 SSOT — 손으로 유지한다.",
		"// label은 source(kiki-barrel→[kiki], kiki-draft→[kiki/draft])에서 파생되므로 여기 적지 않는다.",
		"// 수정 후 `pnpm sync:catalog`로 catalog.generated.ts / registry.generated.ts를 재생성한다.",
		"// candidate→stable 승격은 `pnpm promote:component kiki.<Name>` 사용.",
		"",
		'import type { ComponentCatalogEntry } from "@cx/schema";',
		"",
		'export type CatalogSourceEntry = Omit<ComponentCatalogEntry, "label">;',
		"",
		`export const catalogSource: Record<string, CatalogSourceEntry> = ${serializeTs(source, 0)};`,
		"",
	].join("\n");
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** biome 스타일(탭 들여쓰기, 더블쿼트, trailing comma)에 수렴하는 TS 리터럴 직렬화. */
export function serializeTs(value: unknown, depth: number): string {
	if (value === null) return "null";
	if (typeof value === "string") return JSON.stringify(value);
	if (typeof value === "number" || typeof value === "boolean") return String(value);
	if (Array.isArray(value)) {
		if (value.length === 0) return "[]";
		return `[${value.map((item) => serializeTs(item, depth + 1)).join(", ")}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value as Record<string, unknown>);
		if (entries.length === 0) return "{}";
		// Leaf 객체(중첩 객체 없음)는 한 줄로 — biome은 멀티라인을 유지하므로
		// 기존 생성 파일의 compact 스타일을 emit 시점에 재현해야 한다.
		const isLeaf = entries.every(([, item]) => typeof item !== "object" || Array.isArray(item));
		if (isLeaf) {
			const inline = entries
				.map(([key, item]) => `${quoteKey(key)}: ${serializeTs(item, depth + 1)}`)
				.join(", ");
			// biome lineWidth(100) 추정 초과분은 biome이 다시 펼친다.
			if (depth * 2 + inline.length <= 92) return `{ ${inline} }`;
		}
		const indent = "\t".repeat(depth + 1);
		const body = entries
			.map(([key, item]) => `${indent}${quoteKey(key)}: ${serializeTs(item, depth + 1)},`)
			.join("\n");
		return `{\n${body}\n${"\t".repeat(depth)}}`;
	}
	throw new Error(`Unsupported catalog value: ${typeof value}`);
}

function quoteKey(key: string): string {
	return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}
