// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceScreenCatalog: ReferenceCatalogEntry[] = [
	{
		id: "detail-confirmation",
		situation:
			"사용자가 결제를 실행하기 직전에 주문자·상품·할인·포인트·결제 수단·약관을 한 화면에서 최종 확정한다",
		tags: [
			"detail-confirmation",
			"irreversible-action",
			"summary-first",
			"payment-execution",
			"agreement-gate",
		],
		sotNodeRef: "10161:49136",
		sourceRef: "../docs/references/screens/detail-confirmation/README.md",
	},
	{
		id: "screen-form-entry",
		situation:
			"사용자가 여러 입력값을 제공하거나 확인된 선행 상태를 바탕으로 남은 정보를 입력해 다음 단계로 진행한다",
		tags: ["screen-pattern", "form-entry", "input-heavy", "sectioned-input", "progression-cta"],
		sourceRef: "../docs/references/screens/screen-form-entry/README.md",
	},
];
