// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceScreenCatalog: ReferenceCatalogEntry[] = [
	{
		id: "detail-confirmation",
		situation:
			"사용자가 결제를 실행하기 직전에 주문자·상품·할인·포인트·결제 수단·약관을 한 화면에서 최종 확정한다",
		tags: [
			"detail-confirmation",
			"irreversible-action",
			"summary-first",
			"payment-execution",
			"agreement-gate",
		],
		sotNodeRef: "10161:49136",
		sourceRef: "../docs/references/screens/detail-confirmation/README.md",
	},
	{
		id: "screen-form-entry",
		situation:
			"사용자가 여러 입력값을 제공하거나 확인된 선행 상태를 바탕으로 남은 정보를 입력해 다음 단계로 진행한다",
		tags: ["screen-pattern", "form-entry", "input-heavy", "sectioned-input", "progression-cta"],
		sourceRef: "../docs/references/screens/screen-form-entry/README.md",
	},
	{
		id: "screen-option-configuration",
		situation:
			"사용자가 선택한 상품을 기준으로 할인, USIM/eSIM, 배송 방법, 보상, 배송지 같은 추가 옵션을 섹션별로 선택하거나 보강해 다음 단계로 진행한다",
		tags: [
			"screen-pattern",
			"option-configuration",
			"product-summary",
			"multi-section-selection",
			"progression-cta",
		],
		sourceRef: "../docs/references/screens/screen-option-configuration/README.md",
	},
	{
		id: "screen-payment-completion-detail",
		situation:
			"사용자가 구독/상품 결제를 완료한 뒤 결제 내역, 상품, 배송지, 추천 상품, 안내 문구를 확인하고 후속 action을 선택한다",
		tags: [
			"screen-pattern",
			"payment-completion",
			"completion-result",
			"payment-ledger",
			"subscription-detail",
			"follow-up-actions",
		],
		sotNodeRef: "10090:58801",
		sourceRef: "../docs/references/screens/screen-payment-completion-detail/README.md",
	},
	{
		id: "screen-prooduct-benefit-brand-detail",
		situation:
			"사용자가 특정 제휴 브랜드의 혜택 조건, 이용 유의사항, 관련 쿠폰, 주변 매장, 유사 브랜드를 한 화면에서 탐색한다",
		tags: [
			"screen-pattern",
			"benefit-brand-detail",
			"brand-hero",
			"benefit-information",
			"store-discovery",
			"related-brand-list",
		],
		sotNodeRef: "10069:98025",
		sourceRef: "../docs/references/screens/screen-prooduct-benefit-brand-detail/README.md",
	},
];
