// layoutId → canonical componentKey (registry export). 손작성. behavior-동일 패턴은 한 canonical 공유.
export const layoutAlias: Record<string, string> = {
  // composite (49 → 15)
  // CompositeGap0
  "layout.composite.componentAppBar": "CompositeGap0",
  "layout.composite.componentThumbnailLarge": "CompositeGap0",
  "layout.composite.componentTextField": "CompositeGap0",
  "layout.composite.componentSectionMessage": "CompositeGap0",
  "layout.composite.componentButton": "CompositeGap0",
  "layout.composite.componentListCell": "CompositeGap0",
  "layout.composite.componentAccordion": "CompositeGap0",
  "layout.composite.componentCheckbox": "CompositeGap0",
  "layout.composite.componentCardSummary": "CompositeGap0",
  "layout.composite.componentBadge": "CompositeGap0",
  "layout.composite.componentTextButton": "CompositeGap0",
  "layout.composite.componentListText": "CompositeGap0",
  "layout.composite.componentMapBlock": "CompositeGap0",
  "layout.composite.componentStoreCard": "CompositeGap0",
  "layout.composite.componentTitleSection": "CompositeGap0",
  "layout.composite.componentAccordionNoticeInfo": "CompositeGap0",
  "layout.composite.compositeTitleInfoTextList": "CompositeGap0",
  "layout.composite.compositeSummaryFilteredTextList": "CompositeGap0",
  "layout.composite.compositeSummarySectionedInfoList": "CompositeGap0",
  "layout.composite.compositeTabChipSearchAccordionList": "CompositeGap0",
  "layout.composite.compositeProductHeroMediaInfo": "CompositeGap0",
  "layout.composite.compositeProductListFilterSort": "CompositeGap0",
  "layout.composite.compositePagestackProductCardList": "CompositeGap0",
  "layout.composite.componentActionButton": "CompositeGap0",
  "layout.composite.compositePriceAccordionSelectedList": "CompositeGap0",
  "layout.composite.compositeProductDetailRichImageTab": "CompositeGap0",
  "layout.composite.compositeButtonMoreProductLink": "CompositeGap0",
  "layout.composite.compositeProductDisclosureNoticeList": "CompositeGap0",
  // CompositeGap8
  "layout.composite.componentFooter": "CompositeGap8",
  "layout.composite.compositeStoreMapList": "CompositeGap8",
  "layout.composite.compositeOptionListStack": "CompositeGap8",
  "layout.composite.compositeMapCardInfoList": "CompositeGap8",
  "layout.composite.compositeCardInfoBrandList": "CompositeGap8",
  // CompositeGap12
  "layout.composite.compositeProductSummaryStatusList": "CompositeGap12",
  "layout.composite.compositeListProductHorizontalCardSet": "CompositeGap12",
  "layout.composite.compositeListProductRowCardSet": "CompositeGap12",
  "layout.composite.compositeCouponBenefitCard": "CompositeGap12",
  // unique composites
  "layout.composite.componentProductInfo": "ComponentProductInfoComposite",
  "layout.composite.componentOptionCard": "ComponentOptionCardComposite",
  "layout.composite.componentBannerIndicator": "ComponentBannerIndicatorComposite",
  "layout.composite.componentLegalText": "ComponentLegalTextComposite",
  "layout.composite.componentInfoTextList": "ComponentInfoTextListComposite",
  "layout.composite.componentChipFilter": "ComponentChipFilterComposite",
  "layout.composite.componentTab": "ComponentTabComposite",
  "layout.composite.componentSearchBar": "ComponentSearchBarComposite",
  "layout.composite.compositePlainNoticeList": "CompositePlainNoticeListComposite",
  "layout.composite.compositeFooterLegalLinks": "CompositeFooterLegalLinksComposite",
  "layout.composite.compositeProductListGroupTitleStack": "CompositeProductListGroupTitleStackComposite",
  "layout.composite.componentActionButtonWithTooltip": "ComponentActionButtonWithTooltipComposite",

  // area (30 → 26; 4 aliased, rest self)
  "layout.area.noticeAccordionStackArea": "PlainInfoTextListArea",
  "layout.area.plainInfoTextListArea": "PlainInfoTextListArea",
  "layout.area.tabChipSearchAccordionArea": "FieldStackArea",
  "layout.area.fieldStack": "FieldStackArea",
  "layout.area.listSummaryCardArea": "RowCardListArea",
  "layout.area.rowCardListArea": "RowCardListArea",
  "layout.area.productListGroupArea": "FilterChipTextListArea",
  "layout.area.filterChipTextListArea": "FilterChipTextListArea",
  // area self
  "layout.area.benefitBrandList": "BenefitBrandListArea",
  "layout.area.cardInfoBrandListArea": "CardInfoBrandListArea",
  "layout.area.hiddenTitlePagestackCardListArea": "HiddenTitlePagestackCardListArea",
  "layout.area.horizontalCardListArea": "HorizontalCardListArea",
  "layout.area.mapCardInfoListArea": "MapCardInfoListArea",
  "layout.area.nearbyStoreList": "NearbyStoreListArea",
  "layout.area.optionListSectionArea": "OptionListSectionArea",
  "layout.area.productListChipSortArea": "ProductListChipSortArea",
  "layout.area.productOptionGrid": "ProductOptionGridArea",
  "layout.area.areaAppBar": "AreaAppBarArea",
  "layout.area.areaVertical": "AreaVerticalArea",
  "layout.area.bottomActionArea": "BottomActionArea",
  "layout.area.productFooterLegal": "ProductFooterLegalArea",
  "layout.area.productHeroSummary": "ProductHeroSummaryArea",
  "layout.area.accordionList": "AccordionListArea",
  "layout.area.actionStack": "ActionStackArea",
  "layout.area.authCodeEntry": "AuthCodeEntryArea",
  "layout.area.authMethodList": "AuthMethodListArea",
  "layout.area.listStack": "ListStackArea",
  "layout.area.productDisclosureAccordion": "ProductDisclosureAccordionArea",
  "layout.area.productInfoSection": "ProductInfoSectionArea",
  "layout.area.textListGroupArea": "TextListGroupArea",

  // region (3 → 1)
  "layout.region.header": "PlainStackRegion",
  "layout.region.contents": "PlainStackRegion",
  "layout.region.bottom": "PlainStackRegion",

  // screen (1)
  "layout.screen.mobileScreen": "MobileScreen",
};
