import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { layoutAlias } from "../../packages/layout/src/catalog.alias";
import type { LayoutCatalogEntry } from "../../packages/layout/src/catalog-types";
import { layoutCatalogMetaSchema } from "./schema";

const ROOT = resolve(import.meta.dirname, "..", "..");
const LAYOUT_SRC = join(ROOT, "packages", "layout", "src");
const COMPONENTS_DIR = join(LAYOUT_SRC, "components");
const CATALOG_OUT = join(LAYOUT_SRC, "catalog.generated.ts");
const REGISTRY_OUT = join(LAYOUT_SRC, "registry.generated.ts");

const GEN_HEADER =
	"// AUTO-GENERATED by scripts/sync-layout-catalog — DO NOT EDIT. Run `pnpm sync:layout`.";

function walk(dir: string, predicate: (file: string) => boolean): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...walk(full, predicate));
		else if (entry.isFile() && predicate(full)) out.push(full);
	}
	return out.sort();
}

// ---- 1. collect + validate meta ----------------------------------------

async function collectCatalog(): Promise<Map<string, LayoutCatalogEntry>> {
	const metaFiles = walk(COMPONENTS_DIR, (f) => f.endsWith(".meta.ts"));
	const byId = new Map<string, LayoutCatalogEntry>();

	for (const file of metaFiles) {
		const mod = (await import(pathToFileURL(file).href)) as { meta?: unknown };
		if (mod.meta === undefined) {
			throw new Error(`${relative(ROOT, file)}: missing \`export const meta\``);
		}
		const parsed = layoutCatalogMetaSchema.safeParse(mod.meta);
		if (!parsed.success) {
			throw new Error(
				`${relative(ROOT, file)}: invalid meta\n${JSON.stringify(parsed.error.format(), null, 2)}`,
			);
		}
		const entry = parsed.data as LayoutCatalogEntry;
		if (byId.has(entry.id)) {
			throw new Error(`duplicate catalog id '${entry.id}' (${relative(ROOT, file)})`);
		}
		byId.set(entry.id, entry);
	}
	return byId;
}

// ---- serialization (sorted, byte-stable) --------------------------------

function serializeProp(contract: NonNullable<LayoutCatalogEntry["props"]>[string]): string {
	const c = contract as Record<string, unknown>;
	const parts: string[] = [`type: ${JSON.stringify(c.type)}`];
	if (c.aiWritable !== undefined) parts.push(`aiWritable: ${JSON.stringify(c.aiWritable)}`);
	if (c.description !== undefined) parts.push(`description: ${JSON.stringify(c.description)}`);
	if (c.required !== undefined) parts.push(`required: ${JSON.stringify(c.required)}`);
	if (c.values !== undefined) parts.push(`values: ${JSON.stringify(c.values)}`);
	return `{ ${parts.join(", ")} }`;
}

function serializeEntry(entry: LayoutCatalogEntry): string {
	const lines: string[] = [];
	lines.push(`\t\tid: ${JSON.stringify(entry.id)},`);
	lines.push(`\t\ttarget: ${JSON.stringify(entry.target)},`);
	lines.push(`\t\tname: ${JSON.stringify(entry.name)},`);
	if (entry.props) {
		const propKeys = Object.keys(entry.props).sort();
		lines.push("\t\tprops: {");
		for (const key of propKeys) {
			lines.push(`\t\t\t${JSON.stringify(key)}: ${serializeProp(entry.props[key])},`);
		}
		lines.push("\t\t},");
	}
	if (entry.children) {
		const ch = entry.children;
		const chParts: string[] = [`accepts: ${JSON.stringify(ch.accepts)}`];
		if (ch.max !== undefined) chParts.push(`max: ${JSON.stringify(ch.max)}`);
		if (ch.min !== undefined) chParts.push(`min: ${JSON.stringify(ch.min)}`);
		lines.push(`\t\tchildren: { ${chParts.join(", ")} },`);
	}
	if (entry.description !== undefined) {
		lines.push(`\t\tdescription: ${JSON.stringify(entry.description)},`);
	}
	if (entry.status !== undefined) {
		lines.push(`\t\tstatus: ${JSON.stringify(entry.status)},`);
	}
	return lines.join("\n");
}

function emitCatalog(byId: Map<string, LayoutCatalogEntry>): string {
	const entries = [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));
	const body = entries
		.map((entry) => `\t${JSON.stringify(entry.id)}: {\n${serializeEntry(entry)}\n\t},`)
		.join("\n");
	return [
		GEN_HEADER,
		'import type { LayoutCatalogEntry } from "./catalog-types";',
		"",
		"export const layoutCatalog: Record<string, LayoutCatalogEntry> = {",
		body,
		"};",
		"",
	].join("\n");
}

// ---- 2. registry: canonical key -> exporting .tsx ------------------------

function findCanonicalSources(canonicalKeys: string[]): Map<string, string> {
	const tsxFiles = walk(COMPONENTS_DIR, (f) => f.endsWith(".tsx"));
	const keyToImport = new Map<string, string>();

	for (const file of tsxFiles) {
		const text = readFileSync(file, "utf8");
		for (const key of canonicalKeys) {
			if (keyToImport.has(key)) continue;
			const k = escapeRe(key);
			const patterns = [
				new RegExp(`export\\s+const\\s+${k}\\b`),
				new RegExp(`export\\s+function\\s+${k}\\b`),
				new RegExp(`export\\s*\\{[^}]*\\b${k}\\b[^}]*\\}`), // export { Key } / export { X as Key }
			];
			if (patterns.some((re) => re.test(text))) {
				const noExt = file.replace(/\.tsx$/, "");
				const importPath = `./${relative(LAYOUT_SRC, noExt)}`.split("\\").join("/");
				keyToImport.set(key, importPath);
			}
		}
	}
	return keyToImport;
}

function escapeRe(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function emitRegistry(canonicalKeys: string[]): string {
	const keyToImport = findCanonicalSources(canonicalKeys);
	const missing = canonicalKeys.filter((k) => !keyToImport.has(k));
	if (missing.length > 0) {
		throw new Error(
			`registry: cannot locate exporting .tsx for canonical key(s): ${missing.join(", ")}`,
		);
	}
	const lines = [...keyToImport.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([key, importPath]) => `export { ${key} } from ${JSON.stringify(importPath)};`);
	return [GEN_HEADER, ...lines, ""].join("\n");
}

// ---- main ---------------------------------------------------------------

async function main() {
	const byId = await collectCatalog();
	writeFileSync(CATALOG_OUT, emitCatalog(byId), "utf8");

	const canonicalKeys = [...new Set(Object.values(layoutAlias))];
	writeFileSync(REGISTRY_OUT, emitRegistry(canonicalKeys), "utf8");

	// Normalize to biome's canonical formatting so committed output is byte-stable
	// under both `pnpm sync:layout` and `pnpm format`.
	execFileSync(
		join(ROOT, "node_modules", ".bin", "biome"),
		["format", "--write", CATALOG_OUT, REGISTRY_OUT],
		{ stdio: "ignore" },
	);

	// eslint-disable-next-line no-console
	console.log(
		`sync-layout-catalog: ${byId.size} catalog entries, ${canonicalKeys.length} registry exports`,
	);
}

main().catch((err) => {
	console.error(err instanceof Error ? err.message : err);
	process.exit(1);
});
