// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceAreaCatalog: ReferenceCatalogEntry[] = [
	{
		id: "ref-area-pagestack-section",
		situation:
			"Contents 안에서 제목이 있는 판단 단위나 반복 항목 묶음을 하나의 PageStack 계열 section area로 구성한다",
		tags: ["area-reference", "pagestack", "section-rhythm", "contents-section", "divider"],
		sourceRef: "../docs/skills/references/areas/ref-area-pagestack-section.md",
	},
];
