// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceAreaCatalog: ReferenceCatalogEntry[] = [
	{
		id: "area-form-address",
		situation: "사용자가 주소를 입력하거나 조회된 주소를 확인한 뒤 상세 주소를 보강한다",
		tags: [
			"area-pattern",
			"form-address",
			"address-lookup",
			"readonly-address",
			"field-local-action",
		],
		sourceRef: "../docs/references/areas/area-form-address/README.md",
	},
];
