// AUTO-GENERATED by scripts/sync-reference-catalog — DO NOT EDIT. Run `pnpm sync:reference`.
import type { ReferenceCatalogEntry } from "@cx/schema";

export const referenceAreaCatalog: ReferenceCatalogEntry[] = [
	{
		id: "area-compensation-application",
		situation:
			"사용자가 사용하던 휴대폰 반납 보상 조건을 확인하고 기기 검색 후 바로보상을 신청한다",
		tags: [
			"area-pattern",
			"compensation",
			"device-search",
			"field-local-action",
			"informational-callout",
		],
		sourceRef: "../docs/references/areas/area-compensation-application/README.md",
	},
	{
		id: "area-completion-hero",
		situation:
			"사용자가 신청, 변경, 해지, 제출 같은 주요 업무를 완료했고 결과 상태를 화면 상단에서 강하게 확인해야 한다",
		tags: [
			"area-pattern",
			"completion-result",
			"high-emphasis-status",
			"title-main-complete",
			"result-hero",
		],
		sourceRef: "../docs/references/areas/area-completion-hero/README.md",
	},
	{
		id: "area-completion-result-summary",
		situation:
			"사용자가 개통, 요금제 변경, 신청 처리 같은 주요 업무를 완료했고 결과 headline과 핵심 결과값을 같은 area에서 확인해야 한다",
		tags: [
			"area-pattern",
			"completion-result",
			"result-summary",
			"title-main-complete",
			"summary-card",
		],
		sourceRef: "../docs/references/areas/area-completion-result-summary/README.md",
	},
	{
		id: "area-form-address",
		situation: "사용자가 주소를 입력하거나 조회된 주소를 확인한 뒤 상세 주소를 보강한다",
		tags: [
			"area-pattern",
			"form-address",
			"address-lookup",
			"readonly-address",
			"field-local-action",
		],
		sourceRef: "../docs/references/areas/area-form-address/README.md",
	},
	{
		id: "area-linked-address-field",
		situation:
			"사용자가 주소나 생활지역을 직접 입력하기 전에 기존 가입자/배송지/청구지 정보와 동일하게 재사용할 수 있는 선택지를 먼저 확인해야 한다",
		tags: [
			"area-pattern",
			"linked-address",
			"reuse-existing-info",
			"address-lookup",
			"helper-text",
		],
		sourceRef: "../docs/references/areas/area-linked-address-field/README.md",
	},
	{
		id: "area-linked-recipient-address-field",
		situation:
			"사용자가 배송지나 수령 정보를 기존 가입자 정보와 동일하게 재사용하거나, 수령자 연락처와 주소를 보강한다",
		tags: [
			"area-pattern",
			"linked-recipient-address",
			"reuse-existing-info",
			"recipient-fields",
			"address-lookup",
		],
		sourceRef: "../docs/references/areas/area-linked-recipient-address-field/README.md",
	},
	{
		id: "area-payment-completion-delivery-info",
		situation:
			"사용자가 결제를 완료한 뒤 배송 받을 사람, 연락처, 주소, 배송 메모를 한 area에서 확인한다",
		tags: [
			"area-pattern",
			"payment-completion",
			"delivery-info",
			"address-summary",
			"key-value-list",
		],
		sourceRef: "../docs/references/areas/area-payment-completion-delivery-info/README.md",
	},
	{
		id: "area-payment-completion-ledger",
		situation:
			"사용자가 결제를 완료한 직후 완료 headline과 결제수단, 할인 내역, 최종 결제 금액을 한 area에서 확인한다",
		tags: [
			"area-pattern",
			"payment-completion",
			"completion-result",
			"payment-ledger",
			"final-amount",
		],
		sourceRef: "../docs/references/areas/area-payment-completion-ledger/README.md",
	},
	{
		id: "area-payment-completion-related-product-carousel",
		situation:
			"사용자가 결제를 완료한 뒤 구독 상품과 함께 많이 찾는 관련 상품을 가로 carousel로 탐색한다",
		tags: [
			"area-pattern",
			"payment-completion",
			"related-product",
			"recommendation-carousel",
			"product-card-carousel",
		],
		sourceRef:
			"../docs/references/areas/area-payment-completion-related-product-carousel/README.md",
	},
	{
		id: "area-payment-completion-subscribed-product",
		situation:
			"사용자가 결제를 완료한 뒤 구독된 상품의 이름, 이용 기간/가격, 포함 혜택을 한 area에서 확인한다",
		tags: [
			"area-pattern",
			"payment-completion",
			"subscribed-product",
			"subscription-summary",
			"benefit-list",
		],
		sourceRef: "../docs/references/areas/area-payment-completion-subscribed-product/README.md",
	},
	{
		id: "area-phone-verification-code",
		situation:
			"사용자가 휴대폰 번호를 입력하고 인증을 요청한 뒤, 발송된 인증번호를 제한시간 안에 입력해 본인/연령을 확인한다",
		tags: ["area-pattern", "phone-verification", "auth-code", "countdown-timer", "resend-action"],
		sourceRef: "../docs/references/areas/area-phone-verification-code/README.md",
	},
	{
		id: "area-prerequisite-status",
		situation:
			"사용자가 다음 입력 단계로 진행하기 전에 이미 충족된 선행 조건이나 확인 상태를 짧게 인지해야 한다",
		tags: [
			"area-pattern",
			"prerequisite-status",
			"in-flow-status",
			"auth-completion",
			"readonly-status",
		],
		sourceRef: "../docs/references/areas/area-prerequisite-status/README.md",
	},
	{
		id: "area-product-benefit-brand-hero",
		situation:
			"사용자가 혜택 상세 화면에 진입했을 때 특정 제휴 브랜드의 정체성과 혜택 유형을 첫 화면에서 인지한다",
		tags: [
			"area-pattern",
			"product-benefit-brand",
			"brand-hero",
			"benefit-summary",
			"visual-thumbnail",
		],
		sourceRef: "../docs/references/areas/area-product-benefit-brand-hero/README.md",
	},
	{
		id: "area-product-benefit-coupon-card",
		situation:
			"사용자가 제휴 브랜드 상세 화면에서 받을 수 있거나 사용할 수 있는 쿠폰 혜택을 확인하고 card-local action을 수행한다",
		tags: ["area-pattern", "product-benefit", "coupon", "local-action", "brand-logo-card"],
		sourceRef: "../docs/references/areas/area-product-benefit-coupon-card/README.md",
	},
	{
		id: "area-product-benefit-info-card",
		situation:
			"사용자가 특정 제휴 브랜드에서 제공하는 할인, 적립, 사용 같은 혜택 조건을 유형별로 확인한다",
		tags: [
			"area-pattern",
			"product-benefit",
			"benefit-info",
			"benefit-condition-card",
			"tier-badge-list",
		],
		sourceRef: "../docs/references/areas/area-product-benefit-info-card/README.md",
	},
	{
		id: "area-product-benefit-nearby-store-map",
		situation:
			"사용자가 제휴 브랜드 혜택을 사용할 수 있는 주변 가맹점을 지도와 거리순 목록으로 확인한다",
		tags: [
			"area-pattern",
			"product-benefit",
			"nearby-store",
			"map-preview",
			"store-card-list",
			"local-action",
		],
		sourceRef: "../docs/references/areas/area-product-benefit-nearby-store-map/README.md",
	},
	{
		id: "area-product-benefit-notice-accordion",
		situation:
			"사용자가 제휴 브랜드 혜택의 이용 방법, 제한 조건, 문의처 같은 긴 정책성 안내를 확인한다",
		tags: ["area-pattern", "product-benefit", "notice", "accordion", "policy-copy", "contact-info"],
		sourceRef: "../docs/references/areas/area-product-benefit-notice-accordion/README.md",
	},
	{
		id: "area-product-benefit-related-brand-list",
		situation:
			"사용자가 현재 보고 있는 제휴 브랜드와 비슷한 혜택을 제공하는 다른 브랜드를 탐색한다",
		tags: [
			"area-pattern",
			"product-benefit",
			"related-brand",
			"brand-card-list",
			"benefit-badge-list",
		],
		sourceRef: "../docs/references/areas/area-product-benefit-related-brand-list/README.md",
	},
	{
		id: "area-product-summary-sheet",
		situation:
			"사용자가 이후 옵션을 선택하기 전에 현재 선택한 상품과 월 납부금액을 상단에서 확인한다",
		tags: ["area-pattern", "product-summary", "price-summary", "sheet", "option-context"],
		sourceRef: "../docs/references/areas/area-product-summary-sheet/README.md",
	},
	{
		id: "area-radio-option-group",
		situation: "사용자가 하나의 업무 질문에 대해 여러 상호 배타적인 선택지 중 하나를 고른다",
		tags: [
			"area-pattern",
			"radio-option-group",
			"single-choice",
			"list-selected",
			"optional-callout",
		],
		sourceRef: "../docs/references/areas/area-radio-option-group/README.md",
	},
	{
		id: "area-readonly-identity-field",
		situation:
			"사용자가 입력을 계속하기 전에 기준이 되는 대상 번호, 고객명, 회선 번호 같은 확정 정보를 읽기 전용 field로 확인해야 한다",
		tags: ["area-pattern", "readonly-identity", "reference-field", "disabled-field", "form-entry"],
		sourceRef: "../docs/references/areas/area-readonly-identity-field/README.md",
	},
];
